name: Publish to npm

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run build
      - run: npm publish
