name: Publish to npm

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Sao_Paulo

      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install Packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          npm publish
